### ISSUE TITLE
Voice Chat

### ISSUE THREAD

**Issue by owxys** [Blackhawk-TA/dynoBot#23]
**Describe the bug**
So basically, it wont work and it doesnt say how to make the bot join your vc.
When i do (@mention) addTitle (the song) it says "You can only get the current song when we are in the same voice channel."

![image](https://user-images.githubusercontent.com/62570794/107169214-57d6d600-698b-11eb-8585-951b1a939191.png)

**Comment by Blackhawk-TA** [comment]
Thanks for creating this issue. I can reproduce it.

A title is added by writing `@bot-name add title <song name>`. So there is a space between 'add' and 'title'. Also you have to be in a voice channel so the bot can join you. It will join you automatically when adding a song. 

However, the response of the bot regarding the request is still wrong. I'll take a look at it.

**Comment by Blackhawk-TA** [comment]
Fixed in https://github.com/Blackhawk-TA/dynoBot/pull/24.
If the problem persists, feel free to open a new issue.
