### ISSUE TITLE
@discordjs/opus error

### ISSUE THREAD

**Issue by Xyte** [Blackhawk-TA/dynoBot#29]
**Describe the bug**
Unable to install all required dependencies due to errors with @discordJS.

See below:

npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> @discordjs/opus@0.5.0 install /home/dynoBot/node_modules/@discordjs/opus
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.5.0/opus-v0.5.0-node-v64-napi-v3-linux-x64-glibc-2.28.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for @discordjs/opus@0.5.0 and node@10.24.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.5.0/opus-v0.5.0-node-v64-napi-v3-linux-x64-glibc-2.28.tar.gz
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Linux 4.18.0-240.22.1.el8_3.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/dynoBot/node_modules/@discordjs/opus/prebuild/node-v64-napi-v3-linux-x64-glibc-2.28/opus.node" "--module_name=opus" "--module_path=/home/dynoBot/node_modules/@discordjs/opus/prebuild/node-v64-napi-v3-linux-x64-glibc-2.28" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /home/dynoBot/node_modules/@discordjs/opus
gyp ERR! node -v v10.24.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/dynoBot/node_modules/@discordjs/opus/prebuild/node-v64-napi-v3-linux-x64-glibc-2.28/opus.node --module_name=opus --module_path=/home/dynoBot/node_modules/@discordjs/opus/prebuild/node-v64-napi-v3-linux-x64-glibc-2.28 --napi_version=7 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.cmd.on (/home/dynoBot/node_modules/@discordjs/node-pre-gyp/lib/util/compile.js:85:20)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.18.0-240.22.1.el8_3.x86_64
node-pre-gyp ERR! command "/usr/bin/node" "/home/dynoBot/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/dynoBot/node_modules/@discordjs/opus
node-pre-gyp ERR! node -v v10.24.0
node-pre-gyp ERR! node-pre-gyp -v v0.3.2
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/dynoBot/node_modules/@discordjs/opus/prebuild/node-v64-napi-v3-linux-x64-glibc-2.28/opus.node --module_name=opus --module_path=/home/dynoBot/node_modules/@discordjs/opus/prebuild/node-v64-napi-v3-linux-x64-glibc-2.28 --napi_version=7 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm WARN notsup Unsupported engine for @discordjs/opus@0.5.0: wanted: {"node":">=12.0.0"} (current: {"node":"10.24.0","npm":"6.14.11"})
npm WARN notsup Not compatible with your version of node/npm: @discordjs/opus@0.5.0

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @discordjs/opus@0.5.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @discordjs/opus@0.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-21T11_07_50_219Z-debug.log

**To Reproduce**
1. Clone the repository
2. Run npm install in the repository directory
3. See error

**Expected behavior**
I expect the dependencies to install without errors.

**Screenshots**
https://i.imgur.com/TcAwnqg.png

**Additional context**
To be fair, this could completely be user error - some assistance would be much appreciated.

**Comment by Blackhawk-TA** [comment]
Thanks for the good bug description.
It looks like you are using nodeJs 10.24.0. That’s too old for this project, it requires 14.16.0 or newer.
Could you try updating your nodeJs and npm and run `npm install` again afterwards?

**Comment by Xyte** [comment]
Hi Blackhawk-TA,

Knew it could've been something user related. I'll keep you updated - won't be able to update and test for the next two days.

**Comment by Blackhawk-TA** [comment]
Closed due to inactivity.
