### ISSUE TITLE
Error running npm install

### ISSUE THREAD

**Issue by ShaneAbara** [Blackhawk-TA/dynoBot#3]
`npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for node-source-rcon`

**Comment by Blackhawk-TA** [comment]
Sorry that my answer took this long. For me npm install works fine but I can't find the node-source-rcon module anymore. Therefore I'll switch to an alternative.

**Comment by Blackhawk-TA** [comment]
For now, the deprecated node module is included in the project, so it should work again.
This is only a temporary solution until I switch to another node module.
