### ISSUE TITLE
Why Does Here On Discord It Shows "I Could Not Find This Title"

### ISSUE THREAD

**Issue by swayam-crypto** [Blackhawk-TA/dynoBot#32]
ACOUSTIC BOT : "I could not find this title."

**ScreenShot**
![bug](https://user-images.githubusercontent.com/80890491/142144941-4b583af3-fe47-46d7-9a5a-8670a10f3dbb.PNG)

**Comment by DarrenOfficial** [comment]
any errors in the console?

**Comment by swayam-crypto** [comment]
No Not Error But The Bot Is Not Playing Any Song Its Just Showing In His
Activity That He Is Playing The "Title" of the song

**Comment by Blackhawk-TA** [comment]
This project will soon be archived due to discord's decision to enforce slash commands for bots.
Therefore I won't fix bugs anymore.
For more information take a look at the "End of life" section in the readme file https://github.com/Blackhawk-TA/dynoBot/blob/master/README.md#end-of-life
