### ISSUE TITLE
Feature Update

### ISSUE THREAD

**Issue by swayam-crypto** [Blackhawk-TA/dynoBot#33]
My Feature Is To Add Prefix To Your Project 

**THANKS**

**Comment by Blackhawk-TA** [comment]
This project will soon be archived due to discord's decision to enforce slash commands for bots.
Therefore, I won't add any new features.
For more information take a look at the "End of life" section in the readme file https://github.com/Blackhawk-TA/dynoBot/blob/master/README.md#end-of-life
