### ISSUE TITLE
My bly.at url shortener command is broken :(

### ISSUE THREAD

**Issue by RononDex** [Blackhawk-TA/dynoBot#8]
Pls fix

**Comment by Blackhawk-TA** [comment]
It’s your module. Therefore it is up to you to fix it.
Furthermore other Python modules work fine. This indicates the the bug is within your module and not within the bots core functionality.

**Comment by RononDex** [comment]
B) Missing dependencies?

**Comment by Blackhawk-TA** [comment]
The website bly.at used for shortening the urls does not exist anymore. Either you replace it by another shortener or remove the module.

**Comment by Blackhawk-TA** [comment]
Removed module: https://github.com/Blackhawk-TA/dynoBot/pull/9
